### ISSUE TITLE
Add TheTVDB link

### ISSUE THREAD

**Issue by IAmKontrast** [Tetrax-10/imdb-tmdb-linker#1]
While TheTVDB already contains clickable links to all populated sites, it would be awesome to have an icon for TheTVDB on the other sites (at least TMDB) as well.

Official brand colors and logo: https://support.thetvdb.com/kb/faq.php?id=79

**Comment by Tetrax-10** [comment]
This project primarily focuses on linking IMDb and TMDb pages. I've implemented Letterboxd integration since it doesn't require any API calls or web scraping. It simply involves straightforward page redirection. However, integrating TVDB is beyond the scope of this project, as obtaining TVDB IDs necessitates making API calls.
